#!/bin/sh
set -e -v

for i in 'config.status config.cache config.log configure.lineno config.status.lineno'
do
    test -f ${i} && rm -f ${i}
done
test -f config.h && rm -f config.h
test -f spice-server.pc && rm -f spice-server.pc
test -f server/Makefile && rm -f server/Makefile
test -f client/Makefile && rm -f client/Makefile
test -f Makefile && rm -f Makefile

# packages depended by spice server and libspice.
# spice depends on spice-protocol.

if [ ! -d mylib ]
then
    mkdir mylib
    cd mylib
else
    cd mylib
fi

PREFIX=/usr/local/spice-xen
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:${PREFIX}/share/pkgconfig:/usr/lib/pkgconfig

# qpixman depended library libtool >= 2.2.10
#libtool --version
if [ ! -d libtool-2.2.10 ]
then
    if [ ! -f libtool-2.2.10.tar.gz ]
    then
	wget http://ftp.gnu.org/gnu/libtool/libtool-2.2.10.tar.gz
    fi
    tar -xf libtool-2.2.10.tar.gz
    cd libtool-2.2.10
    ./configure --prefix=/usr
    make
    sudo make install
    cd ..
fi

if [ ! -d qpixman-0.13.3-git20090127 ]
then
    if [ ! -f qpixman-0.13.3-git20090127.tar.bz2 ]
    then
	wget http://spice-space.org/download/stable/qpixman-0.13.3-git20090127.tar.bz2
    fi
    tar xf qpixman-0.13.3-git20090127.tar.bz2
    cd qpixman-0.13.3-git20090127
    ./autogen.sh --prefix=/usr
    make
    sudo make install
    cd ..
fi

if [ ! -d pixman ]
then
  git clone git://anongit.freedesktop.org/pixman
  cd pixman/
  ./autogen.sh --prefix=/usr
  make
  sudo make install
  cd ..  
fi

# qcairo depended library.
if [ ! -d celt-0.5.1.3 ]
then
    if [ ! -f celt-0.5.1.3.tar.gz ]
    then
	wget http://downloads.us.xiph.org/releases/celt/celt-0.5.1.3.tar.gz
    fi
    tar -xf celt-0.5.1.3.tar.gz
    cd celt-0.5.1.3
    ./configure --prefix=/usr
    make
    sudo make install
    cd ..
fi

if [ ! -d qcairo-1.8.7.1-git74d6b5 ]
then
    if [ ! -f qcairo-1.8.7.1-git74d6b5.tar.bz2 ]
    then
	wget http://spice-space.org/download/stable/qcairo-1.8.7.1-git74d6b5.tar.bz2
    fi
    tar xf qcairo-1.8.7.1-git74d6b5.tar.bz2
    cd qcairo-1.8.7.1-git74d6b5/
    ./autogen.sh --prefix=/usr
    make
    sudo make install
    cd ..
fi

cd ..

./configure --prefix=${PREFIX}
