#
# Makefile for Xen components
#

obj-y := hypercall.o xenivt.o xenentry.o xensetup.o xenpal.o \
	 hypervisor.o util.o xencomm.o xcom_hcall.o \
	 xcom_privcmd.o xcom_asm.o xen_dma.o

obj-$(CONFIG_IA64_GENERIC) += machvec.o
